config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :civilian_interests
  resources :shoes
  resources :jobs
  resources :civilians
  resources :interests
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  root 'sessions#new'

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :civilian
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:civilian_id, :job_name)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field field--edit">
    <%= f.label :civilian_id %><br>
    <%= f.text_field :civilian_id, :required => true %>
  </div>
  <div class="field field--edit">
    <%= f.label :job_name %><br>
    <%= f.text_field :job_name, :required => true %>
  </div>
  <div class="actions action--edit">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<div class="edit--civilians">
<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>
</div>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th class="id">ID</th>
      <th>Civilian</th>
      <th>Job name</th>
      <th class="noborder" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td class="id"><%= job.id %></td>
        <td><%= job.civilian.first_name %> <%= job.civilian.last_name %></td>
        <td><%= job.job_name %></td>
        <td class="bttn" ><%= link_to 'Show', job %></td>
	<% if can_access? %>
	        <td class="bttn"><%= link_to 'Edit', edit_job_path(job) %></td>
        	<td class="bttn"><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can_access? %>
	<div class="bttn bttn--new">
		<%= link_to 'New Job', new_job_path %>
	</div>
<%end%>

app/views/jobs/new.html.erb
<div class="edit--civilians">
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>
</div>

app/views/jobs/show.html.erb
<div class="show--jobs">
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @job.id %>
</p>

<p>
  <strong>Civilian:</strong>
  <%= @job.civilian.first_name %>
  <%= @job.civilian.last_name %>
</p>

<p>
  <strong>Job name:</strong>
  <%= @job.job_name %>
</p>

<% if can_access? %>
	<%= link_to 'Edit', edit_job_path(@job) %> |
<%end%>
<%= link_to 'Back', jobs_path %>
</div>