config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :civilian_interests
  resources :shoes
  resources :jobs
  resources :civilians
  resources :interests
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  root 'sessions#new'

end

app/models/civilian_interest.rb
class CivilianInterest < ActiveRecord::Base
	self.table_name = "civilians_interests"
	belongs_to :civilian
  	belongs_to :interest
end

app/controllers/civilian_interests_controller.rb
class CivilianInterestsController < ApplicationController
  before_action :set_civilian_interest, only: [:show, :edit, :update, :destroy]

  # GET /civilian_interests
  # GET /civilian_interests.json
  def index
    @civilian_interests = CivilianInterest.all
  end

  # GET /civilian_interests/1
  # GET /civilian_interests/1.json
  def show
  end

  # GET /civilian_interests/new
  def new
    @civilian_interest = CivilianInterest.new
  end

  # GET /civilian_interests/1/edit
  def edit
  end

  # POST /civilian_interests
  # POST /civilian_interests.json
  def create
    @civilian_interest = CivilianInterest.new(civilian_interest_params)

    respond_to do |format|
      if @civilian_interest.save
        format.html { redirect_to @civilian_interest, notice: 'Civilian interest was successfully created.' }
        format.json { render :show, status: :created, location: @civilian_interest }
      else
        format.html { render :new }
        format.json { render json: @civilian_interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /civilian_interests/1
  # PATCH/PUT /civilian_interests/1.json
  def update
    respond_to do |format|
      if @civilian_interest.update(civilian_interest_params)
        format.html { redirect_to @civilian_interest, notice: 'Civilian interest was successfully updated.' }
        format.json { render :show, status: :ok, location: @civilian_interest }
      else
        format.html { render :edit }
        format.json { render json: @civilian_interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /civilian_interests/1
  # DELETE /civilian_interests/1.json
  def destroy
    @civilian_interest.destroy
    respond_to do |format|
      format.html { redirect_to civilian_interests_url, notice: 'Civilian interest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_civilian_interest
      @civilian_interest = CivilianInterest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def civilian_interest_params
      params.require(:civilian_interest).permit(:civilian_id, :interest_id)
    end
end

app/helpers/civilian_interests_helper.rb
module CivilianInterestsHelper
end

app/views/civilian_interests/_form.html.erb
<%= form_for(@civilian_interest) do |f| %>
  <% if @civilian_interest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@civilian_interest.errors.count, "error") %> prohibited this civilian_interest from being saved:</h2>

      <ul>
      <% @civilian_interest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field field--edit">
    <%= f.label :civilian_id %><br>
    <%= f.text_field :civilian_id, :required => true %>
  </div>
  <div class="field field--edit">
    <%= f.label :interest_id %><br>
    <%= f.text_field :interest_id, :required => true %>
  </div>
  <div class="actions action--edit">
    <%= f.submit %>
  </div>
<% end %>

app/views/civilian_interests/edit.html.erb
<div class="edit--civilians">
<%= render 'form' %>

<%= link_to 'Show', @civilian_interest %> |
<%= link_to 'Back', civilian_interests_path %>
</div>

app/views/civilian_interests/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<h1>Civilian-Interests Relations</h1>

<table>
  <thead>
    <tr>
      <th>Civilian</th>
      <th>Interest</th>
      <th class="noborder" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @civilian_interests.each do |civilian_interest| %>
      <tr>
        <td><%= civilian_interest.civilian.first_name %> <%= civilian_interest.civilian.last_name %></td>
        <td><%= civilian_interest.interest.name %></td>
        <td class="bttn"><%= link_to 'Show', civilian_interest %></td>
	<% if can_access? %>
        	<td class="bttn"><%= link_to 'Edit', edit_civilian_interest_path(civilian_interest) %></td>
        	<td class="bttn"><%= link_to 'Destroy', civilian_interest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can_access? %>
	<div class="bttn bttn--new">
		<%= link_to 'New Civilian-Interest', new_civilian_interest_path %>
	</div>
<%end%>

app/views/civilian_interests/new.html.erb
<div class="edit--ci">
<h1>New Civilian Interest</h1>

<%= render 'form' %>

<%= link_to 'Back', civilian_interests_path %>
</div>

app/views/civilian_interests/show.html.erb
<div class="show--ci">
<p id="notice"><%= notice %></p>

<p>
  <strong>Civilian:</strong>
  <%= @civilian_interest.civilian.first_name %>
  <%= @civilian_interest.civilian.last_name %>
</p>

<p>
  <strong>Interest:</strong>
  <%= @civilian_interest.interest.name%>
</p>

<% if can_access? %>
	<%= link_to 'Edit', edit_civilian_interest_path(@civilian_interest) %> |
<%end%>
<%= link_to 'Back', civilian_interests_path %>
</div>