config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :civilian_interests
  resources :shoes
  resources :jobs
  resources :civilians
  resources :interests
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  root 'sessions#new'

end

app/models/shoe.rb
class Shoe < ActiveRecord::Base
  belongs_to :civilian
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :set_shoe, only: [:show, :edit, :update, :destroy]

  # GET /shoes
  # GET /shoes.json
  def index
    @shoes = Shoe.all
  end

  # GET /shoes/1
  # GET /shoes/1.json
  def show
  end

  # GET /shoes/new
  def new
    @shoe = Shoe.new
  end

  # GET /shoes/1/edit
  def edit
  end

  # POST /shoes
  # POST /shoes.json
  def create
    @shoe = Shoe.new(shoe_params)

    respond_to do |format|
      if @shoe.save
        format.html { redirect_to @shoe, notice: 'Shoe was successfully created.' }
        format.json { render :show, status: :created, location: @shoe }
      else
        format.html { render :new }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoes/1
  # PATCH/PUT /shoes/1.json
  def update
    respond_to do |format|
      if @shoe.update(shoe_params)
        format.html { redirect_to @shoe, notice: 'Shoe was successfully updated.' }
        format.json { render :show, status: :ok, location: @shoe }
      else
        format.html { render :edit }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoes/1
  # DELETE /shoes/1.json
  def destroy
    @shoe.destroy
    respond_to do |format|
      format.html { redirect_to shoes_url, notice: 'Shoe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shoe
      @shoe = Shoe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shoe_params
      params.require(:shoe).permit(:civilian_id, :size, :brand)
    end
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/shoes/_form.html.erb
<%= form_for(@shoe) do |f| %>
  <% if @shoe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shoe.errors.count, "error") %> prohibited this shoe from being saved:</h2>

      <ul>
      <% @shoe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field field--edit">
    <%= f.label :civilian_id %><br>
    <%= f.text_field :civilian_id, :required => true %>
  </div>
  <div class="field field--edit">
    <%= f.label :size %><br>
    <%= f.number_field :size, :required => true %>
  </div>
  <div class="field field--edit">
    <%= f.label :brand %><br>
    <%= f.text_field :brand, :required => true %>
  </div>
  <div class="actions actions--edit">
    <%= f.submit %>
  </div>
<% end %>

app/views/shoes/edit.html.erb
<div class="edit--civilians">
<%= render 'form' %>

<%= link_to 'Show', @shoe %> |
<%= link_to 'Back', shoes_path %>
</div>

app/views/shoes/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<h1>Shoes</h1>

<table>
  <thead>
    <tr>
      <th class="id">ID</th>
      <th>Civilian</th>
      <th>Size</th>
      <th>Brand</th>
      <th class="noborder" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shoes.each do |shoe| %>
      <tr>
        <td class="id"><%= shoe.id %></td>
        <td><%= shoe.civilian.first_name %> <%= shoe.civilian.last_name %></td>
        <td><%= shoe.size %></td>
        <td><%= shoe.brand %></td>
        <td class="bttn"><%= link_to 'Show', shoe %></td>
	<% if can_access? %>
        	<td class="bttn"><%= link_to 'Edit', edit_shoe_path(shoe) %></td>
        	<td class="bttn"><%= link_to 'Destroy', shoe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can_access? %>
	<div class="bttn bttn--new">
		<%= link_to 'New Shoe', new_shoe_path %>
	</div>
<%end%>

app/views/shoes/new.html.erb
<div class="edit--civilians">
<h1>New Shoe</h1>

<%= render 'form' %>

<%= link_to 'Back', shoes_path %>
</div>

app/views/shoes/show.html.erb
<div class="show--shoes">
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @shoe.id %>
</p>

<p>
  <strong>Civilian:</strong>
  <%= @shoe.civilian.first_name %>
  <%= @shoe.civilian.last_name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @shoe.size %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @shoe.brand %>
</p>

<% if current_user.role == "admin" %>
	<%= link_to 'Edit', edit_shoe_path(@shoe) %> |
<%end%>
<%= link_to 'Back', shoes_path %>
</div>