config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :civilian_interests
  resources :shoes
  resources :jobs
  resources :civilians
  resources :interests
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  root 'sessions#new'

end

app/views/layouts/_header.html.erb
<% unless (request.path == sign_in_path) or (request.path == "/users/new") %>
<div class="wrapper-header">
  <header>
    <div>
      <nav>
        <% if logged_in? %>
          <div class="aba"><%= link_to 'Civilians', civilians_path %></div>
          <div class="aba"><%= link_to 'Jobs', jobs_path %></div>
          <div class="aba"><%= link_to 'Interests', interests_path %></div>
          <div class="aba"><%= link_to 'Shoes', shoes_path %></div>
          <div class="aba"><%= link_to 'Civilians-Interests', civilian_interests_path %></div>
          <div class="aba"><%= link_to "Log out", sign_out_path, method: "delete" %></div>
        <% else %>
	    <% controller.redirect_to sign_in_path %>
	<% end %>
      </nav>
    </div>
  </header>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trabalho 5 - Prog. WEB - Aplicação Rails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<% unless request.path == sign_in_path %>
<div class="wrapper">
	<div class="content">
<% end %>
<% unless request.path != sign_in_path %>
<div class="wrapper--sign">
	<div class="content--sign">
<% end %>
		<%= yield %>
	</div>
</div>

</body>
</html>